### PR TITLE
Aesop integration and fundamental groupoid structure

### PR DESCRIPTION
**Pull request by 0art0**
This draft PR attempts to integrate `aesop` into the `Graph` file and prove an instance of the `Groupoid` structure.

### CODE REVIEW

**Comment by siddhartha-gadgil** [comment]
Thanks. I assume this is a "draft" which means that you are going to define the Groupoid structure fully. Can you also define the group given a basepoint (I assume it is a function but I do not know the name).

Also, please split the PR - I still have some issues with the "Turing alternative"

**Comment by siddhartha-gadgil** [comment]
@0art0 I am working on showing reverse is an inverse as well (almost finished left-inverse).

**Comment by 0art0** [comment]
Yes, I intend to fill in the rest of the structure over the next few commits and integrate `aesop` into the file. I will also define the fundamental group for a chosen basepoint by specialising the groupoid definition.

**Comment by 0art0** [comment]
The `TuringAlternative` file was added by mistake. My latest commit removes it.

**Comment by siddhartha-gadgil** [comment]
@0art0 I have proved both inverse properties and setup CI. Whenever you are ready I can merge.

**Comment by 0art0** [comment]
@siddhartha-gadgil I have independently done the same. I think I am ready now, the fundamental groupoid structure is established and `aesop` has been integrated into the file.

**Comment by siddhartha-gadgil** [comment]
@0art0 There are merge conflicts. Can you fix them (then CI will run).

**Pull request merged**
